# Generated by Django 6.0.7 on 2026-07-20 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_alter_subject_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='employee_number',
            field=models.CharField(default='EMP000', max_length=20, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teacher',
            name='subject',
            field=models.CharField(default='exit', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='teacher',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
