# Generated by Django 6.0.7 on 2026-07-21 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_remove_student_class_name_student_school_class'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('term', models.CharField(max_length=20)),
                ('year', models.IntegerField()),
            ],
        ),
    ]
