# Generated by Django 6.0.7 on 2026-07-21 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0009_mark'),
    ]

    operations = [
        migrations.AddField(
            model_name='mark',
            name='grade',
            field=models.CharField(blank=True, max_length=2),
        ),
    ]
