# Generated by Django 6.0.7 on 2026-07-21 19:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0010_mark_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mark',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.exam'),
        ),
        migrations.AlterField(
            model_name='mark',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student'),
        ),
        migrations.AlterField(
            model_name='mark',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.subject'),
        ),
        migrations.AddConstraint(
            model_name='mark',
            constraint=models.UniqueConstraint(fields=('student', 'subject', 'exam'), name='unique_student_subject_exam'),
        ),
    ]
