# Generated by Django 6.0.7 on 2026-07-24 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0016_alter_attendance_date_timetable'),
    ]

    operations = [
        migrations.AddField(
            model_name='feepayment',
            name='mpesa_receipt',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='feepayment',
            name='payment_method',
            field=models.CharField(default='Cash', max_length=20),
        ),
        migrations.AddField(
            model_name='feepayment',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
