# Generated by Django 6.0.7 on 2026-07-24 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0017_feepayment_mpesa_receipt_feepayment_payment_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolprofile',
            name='principal_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='schoolprofile',
            name='principal_signature',
            field=models.ImageField(blank=True, null=True, upload_to='signatures/'),
        ),
    ]
