# Generated by Django 6.0.7 on 2026-07-25 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0019_student_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolprofile',
            name='closing_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='schoolprofile',
            name='opening_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
