# Generated by Django 6.0.7 on 2026-07-25 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0020_schoolprofile_closing_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolprofile',
            name='school_stamp',
            field=models.ImageField(blank=True, null=True, upload_to='school/'),
        ),
    ]
