# Generated by Django 6.0.7 on 2026-07-26 18:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0023_attendance_remarks_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='feepayment',
            old_name='amount_paid',
            new_name='amount',
        ),
        migrations.RemoveField(
            model_name='feepayment',
            name='mpesa_receipt',
        ),
        migrations.RemoveField(
            model_name='feepayment',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='feepayment',
            name='recorded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='feepayment',
            name='reference',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='feepayment',
            name='remarks',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='feepayment',
            name='payment_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='feepayment',
            name='payment_method',
            field=models.CharField(choices=[('Cash', 'Cash'), ('M-Pesa', 'M-Pesa'), ('Bank', 'Bank'), ('Cheque', 'Cheque')], default='Cash', max_length=20),
        ),
    ]
