# Generated by Django 6.0.7 on 2026-07-27 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0026_stocktransaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=200)),
                ('isbn', models.CharField(max_length=30, unique=True)),
                ('category', models.CharField(max_length=100)),
                ('publisher', models.CharField(blank=True, max_length=200)),
                ('publication_year', models.PositiveIntegerField(blank=True, null=True)),
                ('copies', models.PositiveIntegerField(default=1)),
                ('available_copies', models.PositiveIntegerField(default=1)),
                ('shelf', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
