# Generated by Django 6.0.7 on 2026-07-29 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0029_salarystructure_payroll'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salarystructure',
            old_name='nhif',
            new_name='sha',
        ),
    ]
