# Generated by Django 6.0.7

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0029_salarystructure_payroll'),
    ]

    operations = [
    ]