# Generated by Django 6.0.7 on 2026-07-31 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0030_rename_nhif_salarystructure_sha'),
    ]

    operations = [
        migrations.AddField(
            model_name='payroll',
            name='basic_salary',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payroll',
            name='nssf',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='payroll',
            name='other_deductions',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='payroll',
            name='paye',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='payroll',
            name='sha',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
