# Generated by Django 6.0.7 on 2026-07-31 18:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0032_transportroute_studenttransport_vehicle_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transportroute',
            old_name='destination',
            new_name='end_point',
        ),
        migrations.RenameField(
            model_name='transportroute',
            old_name='pickup_point',
            new_name='start_point',
        ),
        migrations.RemoveField(
            model_name='transportroute',
            name='monthly_fee',
        ),
        migrations.AddField(
            model_name='transportroute',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='transportroute',
            name='distance_km',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='transportroute',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transport_routes', to='students.teacher'),
        ),
        migrations.AlterField(
            model_name='transportroute',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='routes', to='students.vehicle'),
        ),
    ]
