# Generated by Django 6.0.7 on 2026-07-31 19:20

import django.db.models.deletion
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0033_rename_destination_transportroute_end_point_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studenttransport',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='studenttransport',
            name='assigned_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studenttransport',
            name='dropoff_point',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='studenttransport',
            name='pickup_point',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='studenttransport',
            name='route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='students.transportroute'),
        ),
        migrations.AlterField(
            model_name='studenttransport',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='transport', to='students.student'),
        ),
    ]
