# Generated by Django 6.0.7 on 2026-08-01 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0036_hostelblock_hostelroom_studenthostel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hostelroom',
            name='occupied',
        ),
    ]
