# Generated by Django 6.0.7 on 2026-08-01 16:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0038_hostelwarden'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostelwarden',
            name='designation',
            field=models.CharField(choices=[('Senior Warden', 'Senior Warden'), ('Assistant Warden', 'Assistant Warden'), ('Night Warden', 'Night Warden'), ('Matron', 'Matron'), ('Patron', 'Patron')], default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hostelwarden',
            name='hostel_block',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wardens', to='students.hostelblock'),
        ),
    ]
