# Generated by Django 6.0.7 on 2026-08-01 17:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0039_hostelwarden_designation_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HostelTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transfer_date', models.DateField(auto_now_add=True)),
                ('reason', models.TextField(blank=True)),
                ('from_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers_from', to='students.hostelroom')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hostel_transfers', to='students.student')),
                ('to_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers_to', to='students.hostelroom')),
                ('transferred_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
