# Generated by Django 6.0.7 on 2026-08-01 21:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0040_hosteltransfer'),
    ]

    operations = [
        migrations.CreateModel(
            name='HostelBed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bed_number', models.CharField(max_length=20)),
                ('occupied', models.BooleanField(default=False)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beds', to='students.hostelroom')),
            ],
            options={
                'ordering': ['bed_number'],
                'unique_together': {('room', 'bed_number')},
            },
        ),
    ]
