# Generated by Django 6.0.7 on 2026-08-02 18:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0043_medication_medicalvisit_hospitalreferral_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dosage', models.CharField(max_length=100)),
                ('frequency', models.CharField(help_text='Example: Twice Daily', max_length=100)),
                ('duration', models.CharField(help_text='Example: 5 Days', max_length=100)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('instructions', models.TextField(blank=True)),
                ('medical_visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='students.medicalvisit')),
                ('medication', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='students.medication')),
            ],
        ),
        migrations.DeleteModel(
            name='MedicalPrescription',
        ),
    ]
