# Generated by Django 6.0.7 on 2026-08-05 06:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0045_remove_teacher_subject_teacher_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='school_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='students.schoolclass'),
        ),
    ]
