# Generated by Django 6.0.7 on 2026-08-05 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0047_exam_status_alter_exam_name_alter_exam_term'),
    ]

    operations = [
        migrations.AddField(
            model_name='mark',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('APPROVED', 'Approved')], default='DRAFT', max_length=20),
        ),
    ]
