# Generated by Django 6.0.7 on 2026-08-06 15:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0052_student_user'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='homeworksubmission',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='homeworksubmission',
            name='graded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='homeworksubmission',
            name='graded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='students.teacher'),
        ),
        migrations.AlterField(
            model_name='homeworksubmission',
            name='submission_file',
            field=models.FileField(default=0, upload_to='homework_submissions/'),
            preserve_default=False,
        ),
    ]
