# Generated by Django 6.0.7 on 2026-08-08 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0055_schooluser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolprofile',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
