# Generated by Django 6.0.7 on 2026-08-08 17:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0058_schoolclass_school_alter_schoolclass_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teachers', to='students.schoolprofile'),
        ),
    ]
