# Generated by Django 6.0.7 on 2026-08-09 12:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0060_subject_school'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolclass',
            name='school',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='students.schoolprofile'),
            preserve_default=False,
        ),
    ]
