# Generated by Django 6.0.7 on 2026-08-09 19:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0062_alter_student_admission_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='students.schoolprofile'),
        ),
    ]
