# Generated by Django 6.0.7 on 2026-08-12 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0063_exam_school'),
    ]

    operations = [
    ]
