# Generated by Django 6.0.7 on 2026-08-12 21:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0064_add_school_to_attendance_timetable'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='timetable',
            name='unique_class_period',
        ),
        migrations.RemoveConstraint(
            model_name='timetable',
            name='unique_teacher_period',
        ),
        migrations.AddField(
            model_name='attendance',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='students.schoolprofile'),
        ),
        migrations.AddField(
            model_name='timetable',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='students.schoolprofile'),
        ),
        migrations.AddConstraint(
            model_name='timetable',
            constraint=models.UniqueConstraint(fields=('school', 'school_class', 'day', 'period'), name='unique_school_class_period'),
        ),
        migrations.AddConstraint(
            model_name='timetable',
            constraint=models.UniqueConstraint(fields=('school', 'teacher', 'day', 'period'), name='unique_school_teacher_period'),
        ),
    ]
