# Generated by Django 6.0.7 on 2026-08-12 21:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0066_populate_attendance_timetable_school'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='school',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='students.schoolprofile'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='timetable',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetables', to='students.schoolprofile'),
        ),
    ]
