# Generated by Django 6.0.7

from django.db import migrations, models
import django.db.models.deletion


def populate_exam_timetable_school(apps, schema_editor):
    ExamTimetable = apps.get_model(
        "students",
        "ExamTimetable"
    )

    for timetable in ExamTimetable.objects.all():

        if timetable.school_class_id:

            timetable.school_id = (
                timetable.school_class.school_id
            )

            timetable.save(
                update_fields=["school"]
            )


class Migration(migrations.Migration):

    dependencies = [
        (
            "students",
            "0067_alter_attendance_school_alter_timetable_school",
        ),
    ]

    operations = [

        # -------------------------------------------------
        # ADD SCHOOL AS NULLABLE TEMPORARILY
        # -------------------------------------------------

        migrations.AddField(
            model_name="examtimetable",
            name="school",
            field=models.ForeignKey(
                to="students.schoolprofile",
                on_delete=django.db.models.deletion.CASCADE,
                null=True,
                blank=True,
            ),
        ),

        # -------------------------------------------------
        # POPULATE SCHOOL FROM SCHOOL CLASS
        # -------------------------------------------------

        migrations.RunPython(
            populate_exam_timetable_school,
            migrations.RunPython.noop,
        ),

        # -------------------------------------------------
        # MAKE SCHOOL REQUIRED
        # -------------------------------------------------

        migrations.AlterField(
            model_name="examtimetable",
            name="school",
            field=models.ForeignKey(
                to="students.schoolprofile",
                on_delete=django.db.models.deletion.CASCADE,
            ),
        ),
    ]