# Generated by Django 6.0.7 on 2026-08-14 12:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0069_driver_school_transportroute_school_vehicle_school_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payroll',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payrolls', to='students.teacher'),
        ),
        migrations.AlterField(
            model_name='transportroute',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transport_routes', to='students.schoolprofile'),
        ),
    ]
