# Generated by Django 6.0.7 on 2026-08-14 13:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0070_alter_payroll_teacher_alter_transportroute_school'),
    ]

    operations = [
        migrations.AddField(
            model_name='payroll',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payrolls', to='students.schoolprofile'),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_records', to='students.teacher'),
        ),
    ]
