# Generated by Django 6.0.7 on 2026-08-15 06:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0072_homework_school_alter_homework_school_class_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homework',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homework', to='students.schoolprofile'),
        ),
    ]
