# Generated by Django 6.0.7 on 2026-08-15 07:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0073_alter_homework_school'),
    ]

    operations = [
        migrations.AddField(
            model_name='disciplinecase',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='discipline_cases', to='students.schoolprofile'),
        ),
        migrations.AddField(
            model_name='disciplinecategory',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='discipline_categories', to='students.schoolprofile'),
        ),
    ]
