# Generated by Django 6.0.7 on 2026-08-15 09:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0074_disciplinecase_school_disciplinecategory_school'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disciplinecase',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discipline_cases', to='students.schoolprofile'),
        ),
        migrations.AlterField(
            model_name='disciplinecategory',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discipline_categories', to='students.schoolprofile'),
        ),
    ]
