# Generated by Django 6.0.7 on 2026-08-15 13:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0075_alter_disciplinecase_school_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='hostelbed',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='hostelroom',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='hostelbed',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hostel_beds', to='students.schoolprofile'),
        ),
        migrations.AddField(
            model_name='hostelblock',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hostel_blocks', to='students.schoolprofile'),
        ),
        migrations.AddField(
            model_name='hostelroom',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hostel_rooms', to='students.schoolprofile'),
        ),
        migrations.AddField(
            model_name='hosteltransfer',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hostel_transfers', to='students.schoolprofile'),
        ),
        migrations.AddField(
            model_name='hostelwarden',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hostel_wardens', to='students.schoolprofile'),
        ),
        migrations.AddField(
            model_name='studenthostel',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_hostels', to='students.schoolprofile'),
        ),
        migrations.AlterField(
            model_name='hostelblock',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='hostelbed',
            unique_together={('school', 'room', 'bed_number')},
        ),
        migrations.AlterUniqueTogether(
            name='hostelblock',
            unique_together={('school', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='hostelroom',
            unique_together={('school', 'block', 'room_number')},
        ),
    ]
