# Generated by Django 6.0.7 on 2026-08-15 14:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0076_alter_hostelbed_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostelbed',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hostel_beds', to='students.schoolprofile'),
        ),
        migrations.AlterField(
            model_name='hostelblock',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hostel_blocks', to='students.schoolprofile'),
        ),
        migrations.AlterField(
            model_name='hostelroom',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hostel_rooms', to='students.schoolprofile'),
        ),
        migrations.AlterField(
            model_name='hosteltransfer',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hostel_transfers', to='students.schoolprofile'),
        ),
        migrations.AlterField(
            model_name='hostelwarden',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hostel_wardens', to='students.schoolprofile'),
        ),
        migrations.AlterField(
            model_name='studenthostel',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_hostels', to='students.schoolprofile'),
        ),
    ]
