# Generated by Django 6.0.7 on 2026-08-15 20:42

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0077_alter_hostelbed_school_alter_hostelblock_school_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hostelbed',
            options={},
        ),
        migrations.RenameField(
            model_name='hostelbed',
            old_name='occupied',
            new_name='is_occupied',
        ),
        migrations.RenameField(
            model_name='hostelroom',
            old_name='block',
            new_name='hostel_block',
        ),
        migrations.RenameField(
            model_name='hostelwarden',
            old_name='active',
            new_name='is_active',
        ),
        migrations.RenameField(
            model_name='studenthostel',
            old_name='active',
            new_name='is_active',
        ),
        migrations.AlterUniqueTogether(
            name='hostelbed',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='hostelblock',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='hostelroom',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='hostelwarden',
            name='designation',
        ),
        migrations.RemoveField(
            model_name='hostelwarden',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='hostelwarden',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='hostelwarden',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='studenthostel',
            name='assigned_date',
        ),
        migrations.RemoveField(
            model_name='studenthostel',
            name='bed_number',
        ),
        migrations.AddField(
            model_name='book',
            name='school',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='library_books', to='students.schoolprofile'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='borrowbook',
            name='school',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='library_borrowings', to='students.schoolprofile'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hostelblock',
            name='capacity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hostelblock',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hostelroom',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='hosteltransfer',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hosteltransfer',
            name='from_bed',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transfers_from', to='students.hostelbed'),
        ),
        migrations.AddField(
            model_name='hosteltransfer',
            name='from_hostel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transfers_from', to='students.hostelblock'),
        ),
        migrations.AddField(
            model_name='hosteltransfer',
            name='to_bed',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transfers_to', to='students.hostelbed'),
        ),
        migrations.AddField(
            model_name='hosteltransfer',
            name='to_hostel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transfers_to', to='students.hostelblock'),
        ),
        migrations.AddField(
            model_name='hostelwarden',
            name='assigned_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hostelwarden',
            name='name',
            field=models.CharField(default='Unknown', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hostelwarden',
            name='remarks',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='hostelwarden',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hostel_warden_assignments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inventorycategory',
            name='school',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='inventory_categories', to='students.schoolprofile'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='school',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='inventory_items', to='students.schoolprofile'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stocktransaction',
            name='school',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='stock_transactions', to='students.schoolprofile'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studenthostel',
            name='admission_date',
            field=models.DateField(
                default=django.utils.timezone.now
            ),
    preserve_default=False,
),
        migrations.AddField(
            model_name='studenthostel',
            name='bed',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_allocations', to='students.hostelbed'),
        ),
        migrations.AddField(
            model_name='studenthostel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studenthostel',
            name='hostel_block',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_allocations', to='students.hostelblock'),
        ),
        migrations.AddField(
            model_name='studenthostel',
            name='leaving_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studenthostel',
            name='remarks',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='borrowbook',
            name='issued_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='hostelbed',
            name='bed_number',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='hostelroom',
            name='capacity',
            field=models.PositiveIntegerField(default=4),
        ),
        migrations.AlterField(
            model_name='hostelroom',
            name='room_number',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='hosteltransfer',
            name='from_room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transfers_from', to='students.hostelroom'),
        ),
        migrations.AlterField(
            model_name='hosteltransfer',
            name='to_room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transfers_to', to='students.hostelroom'),
        ),
        migrations.AlterField(
            model_name='hosteltransfer',
            name='transfer_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='hosteltransfer',
            name='transferred_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hostel_transfers_made', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='hostelwarden',
            name='phone',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='inventorycategory',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='students.inventorycategory'),
        ),
        migrations.AlterField(
            model_name='studenthostel',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_allocations', to='students.hostelroom'),
        ),
        migrations.AlterField(
            model_name='studenthostel',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_hostel_allocations', to='students.schoolprofile'),
        ),
        migrations.AlterField(
            model_name='studenthostel',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hostel_allocations', to='students.student'),
        ),
        migrations.AddConstraint(
            model_name='book',
            constraint=models.UniqueConstraint(fields=('school', 'isbn'), name='unique_book_isbn_per_school'),
        ),
        migrations.AddConstraint(
            model_name='hostelbed',
            constraint=models.UniqueConstraint(fields=('school', 'room', 'bed_number'), name='unique_hostel_bed_per_room'),
        ),
        migrations.AddConstraint(
            model_name='hostelblock',
            constraint=models.UniqueConstraint(fields=('school', 'name'), name='unique_hostel_block_per_school'),
        ),
        migrations.AddConstraint(
            model_name='hostelroom',
            constraint=models.UniqueConstraint(fields=('school', 'hostel_block', 'room_number'), name='unique_hostel_room_per_block'),
        ),
        migrations.AddConstraint(
            model_name='inventorycategory',
            constraint=models.UniqueConstraint(fields=('school', 'name'), name='unique_inventory_category_per_school'),
        ),
        migrations.AddConstraint(
            model_name='inventoryitem',
            constraint=models.UniqueConstraint(fields=('school', 'name'), name='unique_inventory_item_per_school'),
        ),
        migrations.RemoveField(
            model_name='hostelblock',
            name='active',
        ),
    ]
