# Generated by Django 6.0.7 on 2026-08-29 06:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0082_mpesatransaction'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeeLedgerEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.CharField(max_length=20)),
                ('term', models.CharField(max_length=20)),
                ('transaction_date', models.DateField()),
                ('transaction_type', models.CharField(choices=[('OPENING_BALANCE', 'Opening Balance'), ('FEE_CHARGE', 'Fee Charge'), ('PAYMENT', 'Payment'), ('CREDIT', 'Credit'), ('ADJUSTMENT', 'Adjustment'), ('REVERSAL', 'Reversal'), ('CARRY_FORWARD', 'Carry Forward')], max_length=30)),
                ('description', models.CharField(max_length=255)),
                ('debit', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('credit', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('reference', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('fee_payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_entries', to='students.feepayment')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fee_ledger_entries_recorded', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledger_entries', to='students.schoolprofile')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledger_entries', to='students.student')),
            ],
            options={
                'ordering': ['transaction_date', 'id'],
                'indexes': [models.Index(fields=['student', 'transaction_date'], name='students_fe_student_5be1e5_idx'), models.Index(fields=['school', 'academic_year', 'term'], name='students_fe_school__6d4a67_idx')],
            },
        ),
    ]
