# Generated by Django 6.0.7 on 2026-08-30 10:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0083_feeledgerentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='feestructure',
            name='academic_year',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='feestructure',
            name='term',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='feestructure',
            name='school_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_structures', to='students.schoolclass'),
        ),
        migrations.AddConstraint(
            model_name='feestructure',
            constraint=models.UniqueConstraint(fields=('school_class', 'academic_year', 'term'), name='unique_fee_structure_per_class_year_term'),
        ),
    ]
