# Generated by Django 6.0.7 on 2026-08-30 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0084_feestructure_academic_year_feestructure_term_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feestructure',
            name='academic_year',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='feestructure',
            name='term',
            field=models.CharField(max_length=20),
        ),
    ]
