# Generated by Django 6.0.7 on 2026-08-30 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0085_alter_feestructure_academic_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feepayment',
            name='academic_year',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='feepayment',
            name='term',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
