# Generated by Django 6.0.7 on 2026-08-30 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0086_feepayment_academic_year_feepayment_term'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feepayment',
            name='academic_year',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='feepayment',
            name='term',
            field=models.CharField(max_length=20),
        ),
    ]
