# Generated by Django 6.0.7 on 2026-09-02 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0088_feepayment_is_voided_feepayment_void_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='enrollment_academic_year',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='student',
            name='enrollment_term',
            field=models.CharField(default='', max_length=20),
        ),
    ]
