# Generated by Django 6.0.7 on 2026-09-02 17:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0089_student_enrollment_academic_year_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentAcademicEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.CharField(max_length=20)),
                ('term', models.CharField(max_length=20)),
                ('school_class', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='student_enrollments', to='students.schoolclass')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academic_enrollments', to='students.student')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('student', 'academic_year', 'term'), name='unique_student_academic_period')],
            },
        ),
    ]
