# Generated by Django 6.0.7 on 2026-09-04 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0090_studentacademicenrollment'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolclass',
            name='curriculum',
            field=models.CharField(choices=[('CBC', 'CBC'), ('8-4-4', '8-4-4')], default='CBC', max_length=10),
        ),
    ]
