# Generated by Django 6.0.7 on 2026-09-10 15:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0091_schoolclass_curriculum'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurriculumGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(choices=[('PP1', 'PP1'), ('PP2', 'PP2'), ('GRADE1', 'Grade 1'), ('GRADE2', 'Grade 2'), ('GRADE3', 'Grade 3'), ('GRADE4', 'Grade 4'), ('GRADE5', 'Grade 5'), ('GRADE6', 'Grade 6'), ('GRADE7', 'Grade 7'), ('GRADE8', 'Grade 8'), ('GRADE9', 'Grade 9'), ('GRADE10', 'Grade 10'), ('GRADE11', 'Grade 11'), ('GRADE12', 'Grade 12')], max_length=20)),
                ('display_name', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='CurriculumVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Example: CBC 2026', max_length=100)),
                ('code', models.CharField(help_text='Example: CBC-2026', max_length=30, unique=True)),
                ('academic_year', models.CharField(help_text='Academic year this curriculum version applies from.', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-academic_year', '-id'],
            },
        ),
        migrations.CreateModel(
            name='CurriculumPathway',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('ARTS_SPORTS', 'Arts & Sports'), ('STEM', 'STEM'), ('SOCIAL_SCIENCES', 'Social Sciences')], max_length=30)),
                ('description', models.TextField(blank=True)),
                ('curriculum_grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pathways', to='students.curriculumgrade')),
            ],
        ),
        migrations.CreateModel(
            name='CurriculumLearningArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('code', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('assessment_enabled', models.BooleanField(default=True)),
                ('curriculum_grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_areas', to='students.curriculumgrade')),
                ('pathway', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='learning_areas', to='students.curriculumpathway')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='CurriculumStrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(blank=True, max_length=50)),
                ('order', models.PositiveIntegerField(default=1)),
                ('description', models.TextField(blank=True)),
                ('learning_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='strands', to='students.curriculumlearningarea')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CurriculumSubStrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('code', models.CharField(blank=True, max_length=50)),
                ('order', models.PositiveIntegerField(default=1)),
                ('description', models.TextField(blank=True)),
                ('strand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_strands', to='students.curriculumstrand')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CurriculumAssessmentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(choices=[('1', 'Term 1'), ('2', 'Term 2'), ('3', 'Term 3')], max_length=20)),
                ('name', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True)),
                ('maximum_score', models.DecimalField(decimal_places=2, default=100, max_digits=6)),
                ('order', models.PositiveIntegerField(default=1)),
                ('active', models.BooleanField(default=True)),
                ('sub_strand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assessment_items', to='students.curriculumsubstrand')),
            ],
            options={
                'ordering': ['term', 'order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='curriculumgrade',
            name='curriculum_version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='students.curriculumversion'),
        ),
        migrations.AddConstraint(
            model_name='curriculumpathway',
            constraint=models.UniqueConstraint(fields=('curriculum_grade', 'name'), name='unique_grade_pathway'),
        ),
        migrations.AddConstraint(
            model_name='curriculumgrade',
            constraint=models.UniqueConstraint(fields=('curriculum_version', 'grade'), name='unique_curriculum_grade_version'),
        ),
    ]
