# Generated by Django 6.0.7 on 2026-09-10 16:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0092_curriculumgrade_curriculumversion_curriculumpathway_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolClassCurriculum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('curriculum_grade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='school_class_assignments', to='students.curriculumgrade')),
                ('curriculum_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='school_class_assignments', to='students.curriculumversion')),
                ('pathway', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='school_class_assignments', to='students.curriculumpathway')),
                ('school_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curriculum_assignments', to='students.schoolclass')),
            ],
            options={
                'ordering': ['academic_year', 'school_class__name'],
            },
        ),
        migrations.CreateModel(
            name='TeacherAssessmentAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.CharField(max_length=20)),
                ('term', models.CharField(choices=[('1', 'Term 1'), ('2', 'Term 2'), ('3', 'Term 3')], max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('learning_area', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='teacher_assignments', to='students.curriculumlearningarea')),
                ('school_class_curriculum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_assignments', to='students.schoolclasscurriculum')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cbc_assessment_assignments', to='students.teacher')),
            ],
            options={
                'ordering': ['academic_year', 'term', 'school_class_curriculum', 'learning_area'],
            },
        ),
        migrations.CreateModel(
            name='CBCAssessmentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.CharField(max_length=20)),
                ('term', models.CharField(choices=[('1', 'Term 1'), ('2', 'Term 2'), ('3', 'Term 3')], max_length=1)),
                ('assessment_component', models.CharField(choices=[('CAT1', 'CAT 1'), ('MID', 'Mid Term'), ('END', 'End Term')], max_length=10)),
                ('mark', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('performance_level', models.CharField(blank=True, choices=[('EE', 'Exceeds Expectations'), ('ME', 'Meets Expectations'), ('AE', 'Approaches Expectations'), ('BE', 'Below Expectations')], max_length=2)),
                ('points', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('teacher_comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assessment_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assessment_records', to='students.curriculumassessmentitem')),
                ('entered_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cbc_assessment_records_entered', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cbc_assessment_records', to='students.student')),
            ],
            options={
                'ordering': ['academic_year', 'term', 'student', 'assessment_item', 'assessment_component'],
                'constraints': [models.UniqueConstraint(fields=('student', 'assessment_item', 'academic_year', 'term', 'assessment_component'), name='unique_cbc_student_item_component')],
            },
        ),
        migrations.CreateModel(
            name='CBCEndYearLearnerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.CharField(max_length=20)),
                ('core_competencies_achieved', models.TextField(blank=True)),
                ('skills_acquired', models.TextField(blank=True)),
                ('weaknesses_observed', models.TextField(blank=True)),
                ('learner_strengths', models.TextField(blank=True)),
                ('areas_of_improvement', models.TextField(blank=True)),
                ('assessment_date', models.DateField(blank=True, null=True)),
                ('assessor_signature', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assessor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cbc_end_year_profiles_assessed', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cbc_end_year_profiles', to='students.student')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('student', 'academic_year'), name='unique_cbc_end_year_profile')],
            },
        ),
        migrations.AddConstraint(
            model_name='schoolclasscurriculum',
            constraint=models.UniqueConstraint(fields=('school_class', 'academic_year'), name='unique_class_curriculum_year'),
        ),
        migrations.AddConstraint(
            model_name='teacherassessmentassignment',
            constraint=models.UniqueConstraint(fields=('teacher', 'school_class_curriculum', 'learning_area', 'academic_year', 'term'), name='unique_teacher_cbc_assignment'),
        ),
    ]
