# Generated by Django 6.0.7 on 2026-09-10 17:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0093_schoolclasscurriculum_teacherassessmentassignment_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CBCSubStrandAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.PositiveIntegerField()),
                ('term', models.CharField(choices=[('1', 'Term 1'), ('2', 'Term 2'), ('3', 'Term 3')], max_length=1)),
                ('assessment_component', models.CharField(choices=[('CAT1', 'CAT 1'), ('MID', 'Mid-Term'), ('END', 'End-Term')], max_length=10)),
                ('performance_level', models.CharField(blank=True, choices=[('EE', 'Exceeds Expectations'), ('ME', 'Meets Expectations'), ('AE', 'Approaches Expectations'), ('BE', 'Below Expectations')], max_length=2)),
                ('mark', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('teacher_comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entered_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cbc_substrand_assessments_entered', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cbc_substrand_assessments', to='students.student')),
                ('sub_strand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cbc_assessments', to='students.curriculumsubstrand')),
            ],
            options={
                'ordering': ['student', 'sub_strand', 'academic_year', 'term', 'assessment_component'],
                'indexes': [models.Index(fields=['student', 'academic_year', 'term'], name='students_cb_student_9e0d38_idx'), models.Index(fields=['sub_strand', 'academic_year', 'term'], name='students_cb_sub_str_5334c1_idx')],
                'constraints': [models.UniqueConstraint(fields=('student', 'sub_strand', 'academic_year', 'term', 'assessment_component'), name='unique_cbc_substrand_assessment')],
            },
        ),
    ]
