# Generated by Django 6.0.7 on 2026-09-11 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0094_cbcsubstrandassessment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cbcsubstrandassessment',
            name='academic_year',
            field=models.CharField(max_length=20),
        ),
    ]
