# Generated by Django 6.0.7 on 2026-09-11 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0095_alter_cbcsubstrandassessment_academic_year'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='curriculumlearningarea',
            constraint=models.UniqueConstraint(condition=models.Q(('pathway__isnull', True)), fields=('curriculum_grade', 'name'), name='unique_lower_grade_learning_area'),
        ),
        migrations.AddConstraint(
            model_name='curriculumlearningarea',
            constraint=models.UniqueConstraint(fields=('curriculum_grade', 'pathway', 'name'), name='unique_pathway_learning_area'),
        ),
    ]
