# Generated by Django 6.0.7 on 2026-09-11 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0096_curriculumlearningarea_unique_lower_grade_learning_area_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='curriculumstrand',
            constraint=models.UniqueConstraint(condition=models.Q(('code', ''), _negated=True), fields=('learning_area', 'code'), name='unique_strand_code_per_learning_area'),
        ),
    ]
