# Generated by Django 6.0.7 on 2026-09-11 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0097_curriculumstrand_unique_strand_code_per_learning_area'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='curriculumsubstrand',
            constraint=models.UniqueConstraint(condition=models.Q(('code', ''), _negated=True), fields=('strand', 'code'), name='unique_substrand_code_per_strand'),
        ),
    ]
