# Generated by Django 6.0.7 on 2026-09-11 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0098_curriculumsubstrand_unique_substrand_code_per_strand'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='curriculumassessmentitem',
            constraint=models.UniqueConstraint(fields=('sub_strand', 'term', 'name'), name='unique_assessment_item_per_substrand_term'),
        ),
    ]
