# Generated by Django 6.0.7 on 2026-09-11 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0099_curriculumassessmentitem_unique_assessment_item_per_substrand_term'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cbcsubstrandassessment',
            options={},
        ),
        migrations.RenameIndex(
            model_name='cbcsubstrandassessment',
            new_name='cbc_assess_student_period_idx',
            old_name='students_cb_student_9e0d38_idx',
        ),
        migrations.RenameIndex(
            model_name='cbcsubstrandassessment',
            new_name='cbc_assess_substrand_idx',
            old_name='students_cb_sub_str_5334c1_idx',
        ),
    ]
