# Generated by Django 6.0.7 on 2026-09-14 11:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0100_alter_cbcsubstrandassessment_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolprofile',
            name='curriculum_system',
            field=models.CharField(choices=[('CBC', 'CBC'), ('8-4-4', '8-4-4'), ('BOTH', 'Both CBC & 8-4-4')], default='CBC', max_length=10),
        ),
        migrations.AlterField(
            model_name='feeledgerentry',
            name='recorded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_entries_recorded', to=settings.AUTH_USER_MODEL),
        ),
    ]
