# Generated by Django 6.0.7 on 2026-09-14 21:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0101_schoolprofile_curriculum_system_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CBCAssessmentSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.CharField(max_length=20)),
                ('term', models.CharField(choices=[('1', 'Term 1'), ('2', 'Term 2'), ('3', 'Term 3')], max_length=1)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='DRAFT', max_length=20)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_cbc_assessment_submissions', to=settings.AUTH_USER_MODEL)),
                ('learning_area', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assessment_submissions', to='students.curriculumlearningarea')),
                ('school_class_curriculum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_submissions', to='students.schoolclasscurriculum')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cbc_assessment_submissions', to='students.teacher')),
            ],
            options={
                'ordering': ['academic_year', 'term', 'school_class_curriculum', 'learning_area'],
            },
        ),
        migrations.AddField(
            model_name='cbcsubstrandassessment',
            name='submission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='students.cbcassessmentsubmission'),
        ),
        migrations.AddConstraint(
            model_name='cbcassessmentsubmission',
            constraint=models.UniqueConstraint(fields=('school_class_curriculum', 'learning_area', 'academic_year', 'term'), name='unique_cbc_assessment_submission'),
        ),
    ]
