# Generated by Django 6.0.7 on 2026-09-15
#
# Safe migration for existing CBC sub-strand assessments.
#
# Existing EE/ME/AE/BE values are preserved in
# legacy_performance_level before performance_level becomes
# a foreign key.

from decimal import Decimal

from django.db import migrations, models
import django.db.models.deletion


def preserve_old_performance_levels(apps, schema_editor):
    """
    Preserve the old text performance level.

    Existing records contain values such as:
        EE
        ME
        AE
        BE

    These values are copied to legacy_performance_level.

    We intentionally do NOT invent EE1/EE2/etc. because the old
    records do not contain marks from which the exact level can
    be determined.
    """

    Assessment = apps.get_model(
        "students",
        "CBCSubStrandAssessment",
    )

    db_alias = schema_editor.connection.alias

    for assessment in Assessment.objects.using(db_alias).all():

        old_level = assessment.performance_level

        if old_level:
            assessment.legacy_performance_level = old_level

        assessment.performance_level = None

        assessment.save(
            using=db_alias,
            update_fields=[
                "legacy_performance_level",
                "performance_level",
            ],
        )


def seed_grade10_performance_levels(apps, schema_editor):
    """
    Create the agreed Grade 10-12 performance scale.
    """

    CurriculumGrade = apps.get_model(
        "students",
        "CurriculumGrade",
    )

    CBCPerformanceLevel = apps.get_model(
        "students",
        "CBCPerformanceLevel",
    )

    db_alias = schema_editor.connection.alias

    grade10 = (
        CurriculumGrade.objects
        .using(db_alias)
        .filter(grade="GRADE10")
        .first()
    )

    if not grade10:
        return

    performance_levels = [
        {
            "category": "EE",
            "code": "EE1",
            "minimum_mark": Decimal("90"),
            "maximum_mark": Decimal("99"),
            "points": Decimal("8"),
            "order": 1,
        },
        {
            "category": "EE",
            "code": "EE2",
            "minimum_mark": Decimal("75"),
            "maximum_mark": Decimal("89"),
            "points": Decimal("7"),
            "order": 2,
        },
        {
            "category": "ME",
            "code": "ME1",
            "minimum_mark": Decimal("58"),
            "maximum_mark": Decimal("74"),
            "points": Decimal("6"),
            "order": 3,
        },
        {
            "category": "ME",
            "code": "ME2",
            "minimum_mark": Decimal("41"),
            "maximum_mark": Decimal("57"),
            "points": Decimal("5"),
            "order": 4,
        },
        {
            "category": "AE",
            "code": "AE1",
            "minimum_mark": Decimal("31"),
            "maximum_mark": Decimal("40"),
            "points": Decimal("4"),
            "order": 5,
        },
        {
            "category": "AE",
            "code": "AE2",
            "minimum_mark": Decimal("21"),
            "maximum_mark": Decimal("30"),
            "points": Decimal("3"),
            "order": 6,
        },
        {
            "category": "BE",
            "code": "BE1",
            "minimum_mark": Decimal("11"),
            "maximum_mark": Decimal("20"),
            "points": Decimal("2"),
            "order": 7,
        },
        {
            "category": "BE",
            "code": "BE2",
            "minimum_mark": Decimal("1"),
            "maximum_mark": Decimal("10"),
            "points": Decimal("1"),
            "order": 8,
        },
    ]

    for item in performance_levels:

        CBCPerformanceLevel.objects.using(db_alias).get_or_create(
            curriculum_grade=grade10,
            code=item["code"],
            defaults={
                "category": item["category"],
                "minimum_mark": item["minimum_mark"],
                "maximum_mark": item["maximum_mark"],
                "points": item["points"],
                "order": item["order"],
            },
        )


class Migration(migrations.Migration):

    dependencies = [
        (
            "students",
            "0102_cbcassessmentsubmission_and_more",
        ),
    ]

    operations = [

        # ---------------------------------------------------------
        # 1. Add points
        # ---------------------------------------------------------

        migrations.AddField(
            model_name="cbcsubstrandassessment",
            name="points",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=5,
                null=True,
            ),
        ),

        # ---------------------------------------------------------
        # 2. Add a legacy field for the existing EE/ME/AE/BE data
        # ---------------------------------------------------------

        migrations.AddField(
            model_name="cbcsubstrandassessment",
            name="legacy_performance_level",
            field=models.CharField(
                blank=True,
                editable=False,
                max_length=2,
            ),
        ),

        # ---------------------------------------------------------
        # 3. Keep existing CBCAssessmentRecord compatible
        # ---------------------------------------------------------

        migrations.AlterField(
            model_name="cbcassessmentrecord",
            name="performance_level",
            field=models.CharField(
                blank=True,
                max_length=10,
            ),
        ),

        # ---------------------------------------------------------
        # 4. Temporarily make the OLD text field nullable.
        #
        # This is the critical step missing from the previous
        # migration.
        # ---------------------------------------------------------

        migrations.AlterField(
            model_name="cbcsubstrandassessment",
            name="performance_level",
            field=models.CharField(
                blank=True,
                max_length=2,
                null=True,
            ),
        ),

        # ---------------------------------------------------------
        # 5. Create the new performance-level table
        # ---------------------------------------------------------

        migrations.CreateModel(
            name="CBCPerformanceLevel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            (
                                "EE",
                                "Exceeding Expectation",
                            ),
                            (
                                "ME",
                                "Meeting Expectation",
                            ),
                            (
                                "AE",
                                "Approaching Expectation",
                            ),
                            (
                                "BE",
                                "Below Expectation",
                            ),
                        ],
                        max_length=2,
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=10,
                    ),
                ),
                (
                    "minimum_mark",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                    ),
                ),
                (
                    "maximum_mark",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                    ),
                ),
                (
                    "points",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=1,
                    ),
                ),
                (
                    "curriculum_grade",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="performance_levels",
                        to="students.curriculumgrade",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),

        # ---------------------------------------------------------
        # 6. Preserve old EE/ME/AE/BE values.
        # ---------------------------------------------------------

        migrations.RunPython(
            preserve_old_performance_levels,
            migrations.RunPython.noop,
        ),

        # ---------------------------------------------------------
        # 7. Seed Grade 10 performance scale
        # ---------------------------------------------------------

        migrations.RunPython(
            seed_grade10_performance_levels,
            migrations.RunPython.noop,
        ),

        # ---------------------------------------------------------
        # 8. Convert performance_level to the new FK
        # ---------------------------------------------------------

        migrations.AlterField(
            model_name="cbcsubstrandassessment",
            name="performance_level",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="assessments",
                to="students.cbcperformancelevel",
            ),
        ),

        # ---------------------------------------------------------
        # 9. Unique performance code per curriculum grade
        # ---------------------------------------------------------

        migrations.AddConstraint(
            model_name="cbcperformancelevel",
            constraint=models.UniqueConstraint(
                fields=(
                    "curriculum_grade",
                    "code",
                ),
                name="unique_cbc_performance_code_per_grade",
            ),
        ),
    ]