# Generated by Django 6.0.7 on 2026-09-18 00:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0103_cbcsubstrandassessment_points_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CBCStrandSummativeAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.CharField(max_length=20)),
                ('term', models.CharField(choices=[('1', 'Term 1'), ('2', 'Term 2'), ('3', 'Term 3')], max_length=1)),
                ('assessment_component', models.CharField(choices=[('CAT1', 'CAT 1'), ('MID', 'Mid-Term'), ('END', 'End-Term')], max_length=10)),
                ('performance_level', models.PositiveSmallIntegerField(blank=True, choices=[(1, '1 — BE — Below Expectations'), (2, '2 — AE — Approaching Expectations'), (3, '3 — ME — Meeting Expectations'), (4, '4 — EE — Exceeding Expectations')], null=True)),
                ('teacher_comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entered_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cbc_strand_summatives_entered', to=settings.AUTH_USER_MODEL)),
                ('strand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='summative_assessments', to='students.curriculumstrand')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cbc_strand_summative_assessments', to='students.student')),
                ('submission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='strand_summatives', to='students.cbcassessmentsubmission')),
            ],
            options={
                'indexes': [models.Index(fields=['student', 'academic_year', 'term'], name='cbc_summ_student_period'), models.Index(fields=['strand', 'academic_year', 'term'], name='cbc_summ_strand_period')],
                'constraints': [models.UniqueConstraint(fields=('student', 'strand', 'academic_year', 'term', 'assessment_component'), name='unique_cbc_strand_summative')],
            },
        ),
    ]
