# Generated by Django 6.0.7 on 2026-09-18 02:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0104_cbcstrandsummativeassessment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CBCSubjectAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.CharField(max_length=20)),
                ('term', models.CharField(choices=[('1', 'Term 1'), ('2', 'Term 2'), ('3', 'Term 3')], max_length=1)),
                ('assessment_component', models.CharField(choices=[('CAT1', 'CAT 1'), ('MID', 'Mid-Term'), ('END', 'End-Term')], max_length=10)),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('performance_level', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'BE'), (2, 'AE'), (3, 'ME'), (4, 'EE')], null=True)),
                ('teacher_comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entered_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cbc_subject_assessments_entered', to=settings.AUTH_USER_MODEL)),
                ('learning_area', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subject_assessments', to='students.curriculumlearningarea')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cbc_subject_assessments', to='students.student')),
            ],
            options={
                'indexes': [models.Index(fields=['student', 'academic_year', 'term'], name='cbc_subject_assess_student_period_idx'), models.Index(fields=['learning_area', 'academic_year', 'term'], name='cbc_subject_assess_area_period_idx')],
                'constraints': [models.UniqueConstraint(fields=('student', 'learning_area', 'academic_year', 'term', 'assessment_component'), name='unique_cbc_subject_assessment')],
            },
        ),
    ]
