# Generated by Django 6.0.7 on 2026-09-18 03:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0105_cbcsubjectassessment'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='cbcsubjectassessment',
            new_name='cbc_subj_stu_period_idx',
            old_name='cbc_subject_assess_student_period_idx',
        ),
        migrations.RenameIndex(
            model_name='cbcsubjectassessment',
            new_name='cbc_subj_area_period_idx',
            old_name='cbc_subject_assess_area_period_idx',
        ),
    ]
