# Generated by Django 6.0.7 on 2026-09-18 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0106_rename_cbc_subject_assess_student_period_idx_cbc_subj_stu_period_idx_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teacherassessmentassignment',
            options={},
        ),
        migrations.RemoveConstraint(
            model_name='teacherassessmentassignment',
            name='unique_teacher_cbc_assignment',
        ),
        migrations.AddConstraint(
            model_name='teacherassessmentassignment',
            constraint=models.UniqueConstraint(fields=('teacher', 'school_class_curriculum', 'learning_area', 'academic_year'), name='unique_teacher_cbc_assignment'),
        ),
    ]
