# Generated by Django 6.0.7 on 2026-09-18 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0107_alter_teacherassessmentassignment_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacherassessmentassignment',
            name='term',
        ),
    ]
