# Generated by Django 6.0.7 on 2026-09-19 18:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0108_remove_teacherassessmentassignment_term'),
    ]

    operations = [
        migrations.AddField(
            model_name='cbcsubjectassessment',
            name='submission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subject_assessments', to='students.cbcassessmentsubmission'),
        ),
    ]
