# Generated by Django 6.0.7 on 2026-09-20 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0109_cbcsubjectassessment_submission'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='marks_out_of',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=6),
        ),
    ]
