# Generated by Django 6.0.7 on 2026-09-20 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0110_exam_marks_out_of'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='marks_out_of',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
