# Generated by Django 6.0.7 on 2026-09-21 09:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0111_alter_exam_marks_out_of'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='cbcassessmentsubmission',
            name='unique_cbc_assessment_submission',
        ),
        migrations.AddField(
            model_name='cbcassessmentsubmission',
            name='assessment_component',
            field=models.CharField(blank=True, choices=[('CAT1', 'CAT 1'), ('MID', 'Mid-Term'), ('END', 'End-Term')], max_length=10, null=True),
        ),
        migrations.AddConstraint(
            model_name='cbcassessmentsubmission',
            constraint=models.UniqueConstraint(fields=('school_class_curriculum', 'learning_area', 'academic_year', 'term', 'assessment_component'), name='unique_cbc_assessment_submission'),
        ),
    ]
