# Generated by Django 6.0.7 on 2026-09-21 21:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0112_remove_cbcassessmentsubmission_unique_cbc_assessment_submission_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolAcademicYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=20)),
                ('opening_date', models.DateField(blank=True, null=True)),
                ('closing_date', models.DateField(blank=True, null=True)),
                ('is_current', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academic_years', to='students.schoolprofile')),
            ],
            options={
                'ordering': ['-year'],
                'indexes': [models.Index(fields=['school', 'year'], name='school_academic_year_idx')],
                'constraints': [models.UniqueConstraint(fields=('school', 'year'), name='unique_school_academic_year')],
            },
        ),
    ]
