# Generated by Django 6.0.7 on 2026-09-22 23:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0113_schoolacademicyear'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CBCUpperSecondaryAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.CharField(max_length=20)),
                ('term', models.CharField(choices=[('1', 'Term 1'), ('2', 'Term 2'), ('3', 'Term 3')], max_length=1)),
                ('assessment_component', models.CharField(choices=[('CAT1', 'CAT 1'), ('MID', 'MID TERM'), ('END', 'END TERM')], max_length=10)),
                ('raw_score', models.DecimalField(decimal_places=2, max_digits=6)),
                ('marks_out_of', models.DecimalField(decimal_places=2, max_digits=6)),
                ('percentage_score', models.DecimalField(decimal_places=2, max_digits=6)),
                ('points', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('teacher_comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entered_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='upper_secondary_assessments_entered', to=settings.AUTH_USER_MODEL)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='upper_secondary_assessments', to='students.exam')),
                ('learning_area', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='upper_secondary_assessments', to='students.curriculumlearningarea')),
                ('performance_level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='upper_secondary_assessments', to='students.cbcperformancelevel')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upper_secondary_assessments', to='students.student')),
                ('submission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='upper_secondary_assessments', to='students.cbcassessmentsubmission')),
            ],
            options={
                'ordering': ['academic_year', 'term', 'assessment_component', 'student'],
                'indexes': [models.Index(fields=['academic_year', 'term', 'assessment_component'], name='upper_sec_year_term_component_idx'), models.Index(fields=['student', 'academic_year', 'term'], name='upper_sec_student_year_term_idx')],
                'constraints': [models.UniqueConstraint(fields=('student', 'learning_area', 'academic_year', 'term', 'assessment_component'), name='unique_upper_secondary_assessment')],
            },
        ),
    ]
