# Generated by Django 6.0.7 on 2026-09-22 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0114_cbcuppersecondaryassessment'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='cbcstrandsummativeassessment',
            name='cbc_summ_student_period',
        ),
        migrations.RemoveIndex(
            model_name='cbcstrandsummativeassessment',
            name='cbc_summ_strand_period',
        ),
        migrations.RenameIndex(
            model_name='cbcuppersecondaryassessment',
            new_name='cbc_upper_yr_term',
            old_name='upper_sec_year_term_component_idx',
        ),
        migrations.RenameIndex(
            model_name='cbcuppersecondaryassessment',
            new_name='cbc_upper_stu_term',
            old_name='upper_sec_student_year_term_idx',
        ),
    ]
