# Generated by Django 6.0.7 on 2026-09-24 10:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0115_remove_cbcstrandsummativeassessment_cbc_summ_student_period_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CBCUpperSecondaryStrandSummativeAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.CharField(max_length=20)),
                ('term', models.CharField(choices=[('1', 'Term 1'), ('2', 'Term 2'), ('3', 'Term 3')], max_length=1)),
                ('assessment_component', models.CharField(choices=[('CAT1', 'CAT 1'), ('MID', 'MID TERM'), ('END', 'END TERM')], max_length=10)),
                ('performance_level', models.CharField(blank=True, choices=[('EE', 'EE — Exceeding Expectations'), ('ME', 'ME — Meeting Expectations'), ('AE', 'AE — Approaching Expectations'), ('BE', 'BE — Below Expectations')], max_length=2, null=True)),
                ('teacher_comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entered_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='upper_secondary_strand_summatives_entered', to=settings.AUTH_USER_MODEL)),
                ('learning_area', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='upper_secondary_strand_summatives', to='students.curriculumlearningarea')),
                ('strand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='upper_secondary_strand_summatives', to='students.curriculumstrand')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upper_secondary_strand_summative_assessments', to='students.student')),
                ('submission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='upper_secondary_strand_summatives', to='students.cbcassessmentsubmission')),
            ],
            options={
                'ordering': ['academic_year', 'term', 'assessment_component', 'student'],
                'indexes': [models.Index(fields=['academic_year', 'term', 'assessment_component'], name='cbc_upper_summ_yr_term'), models.Index(fields=['student', 'academic_year', 'term'], name='cbc_upper_summ_stu_term'), models.Index(fields=['learning_area', 'academic_year', 'term'], name='cbc_upper_summ_la_term'), models.Index(fields=['strand', 'academic_year', 'term'], name='cbc_upper_summ_strand_term')],
                'constraints': [models.UniqueConstraint(fields=('student', 'strand', 'academic_year', 'term', 'assessment_component'), name='unique_upper_secondary_strand_summative')],
            },
        ),
        migrations.CreateModel(
            name='CBCUpperSecondarySubStrandAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.CharField(max_length=20)),
                ('term', models.CharField(choices=[('1', 'Term 1'), ('2', 'Term 2'), ('3', 'Term 3')], max_length=1)),
                ('assessment_component', models.CharField(choices=[('CAT1', 'CAT 1'), ('MID', 'MID TERM'), ('END', 'END TERM')], max_length=10)),
                ('performance_level', models.CharField(choices=[('EE', 'EE — Exceeding Expectations'), ('ME', 'ME — Meeting Expectations'), ('AE', 'AE — Approaching Expectations'), ('BE', 'BE — Below Expectations')], max_length=2)),
                ('teacher_comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entered_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='upper_secondary_substrand_assessments_entered', to=settings.AUTH_USER_MODEL)),
                ('learning_area', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='upper_secondary_substrand_assessments', to='students.curriculumlearningarea')),
                ('strand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='upper_secondary_substrand_assessments', to='students.curriculumstrand')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upper_secondary_substrand_assessments', to='students.student')),
                ('sub_strand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='upper_secondary_substrand_assessments', to='students.curriculumsubstrand')),
                ('submission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='upper_secondary_substrand_assessments', to='students.cbcassessmentsubmission')),
            ],
            options={
                'ordering': ['academic_year', 'term', 'assessment_component', 'student'],
                'indexes': [models.Index(fields=['academic_year', 'term', 'assessment_component'], name='cbc_upper_ss_yr_term'), models.Index(fields=['student', 'academic_year', 'term'], name='cbc_upper_ss_stu_term'), models.Index(fields=['learning_area', 'academic_year', 'term'], name='cbc_upper_ss_la_term'), models.Index(fields=['sub_strand', 'academic_year', 'term'], name='cbc_upper_ss_term')],
                'constraints': [models.UniqueConstraint(fields=('student', 'sub_strand', 'academic_year', 'term', 'assessment_component'), name='unique_upper_secondary_substrand_assessment')],
            },
        ),
    ]
