# Generated by Django 6.0.7 on 2026-09-25 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0116_cbcuppersecondarystrandsummativeassessment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolprofile',
            name='subscription_tier',
            field=models.CharField(choices=[('T1', 'Tier 1 - Academic + Parents + SMS'), ('T2', 'Tier 2 - Finance'), ('T3', 'Tier 3 - Transport'), ('T4', 'Tier 4 - School Operations'), ('T5', 'Tier 5 - Resources'), ('T6', 'Tier 6 - Full School Management')], default='T1', max_length=2),
        ),
    ]
