from .admin_modules.academic import *
from .admin_modules.examination import *
from .admin_modules.finance import *
from .admin_modules.discipline import *
from .admin_modules.medical import *
from .admin_modules.hostel import *
from .admin_modules.transport import *
from .admin_modules.inventory import *
from .admin_modules.library import *
from .admin_modules.payroll import *
from .admin_modules.administration import *